services:
  web:
    build: .
    environment:
      DATABASE_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      # POSTGRES_PASSWORD: password
      # POSTGRES_HOST_AUTH_METHOD: trust
